name: frappe
version: 0.3.2+1
description: A slightly Bacon.js inspired package to make reactive programming easier in Dart.
author: Dan Schultz <schultz.t.dan@gmail.com>
homepage: http://www.github.com/danschultz/frappe
environment:
  sdk: ^1.8.0
dependencies:
  stream_transformers: ^0.3.0
dev_dependencies:
  guinness: ^0.1.6
