name: frappe
version: 0.3.2
description: A slightly Bacon.js inspired package to make reactive programming easier in Dart.
author: Dan Schultz <schultz.t.dan@gmail.com>
homepage: http://www.github.com/danschultz/frappe
dependencies:
dev_dependencies:
  guinness: '>=0.1.6 <0.2.0'
