name: frappe
version: 0.4.0+4
description: >
  A functional reactive programming library for Dart. Frappé extends the functionality
  of Dart's streams, and introduces new concepts like properties/signals.
author: Dan Schultz <schultz.t.dan@gmail.com>
homepage: http://www.github.com/danschultz/frappe
environment:
  sdk: '>=1.8.0'
dependencies:
  stream_transformers: ^0.3.0
dev_dependencies:
  browser: ^0.10.0
  guinness: ^0.1.6
