name: relay
version: 0.1.0
description: An experimental reactive programming package for Dart.
author: Dan Schultz <schultz.t.dan@gmail.com>
homepage: http://www.github.com/danschultz/relay
dependencies:
dev_dependencies:
  guinness: '>=0.1.6 <0.2.0'
  hop: '>=0.31.0 <0.32.0'
  hop_unittest: '>=0.1.0 <0.2.0'
