author: "Dan Schultz <schultz.t.dan@gmail.com>"
description: "A slightly Bacon.js inspired package to make reactive programming easier in Dart."
homepage: "http://www.github.com/danschultz/frappe"
name: "frappe"
version: "0.3.1"
dev_dependencies: 
  guinness: ">=0.1.6 <0.2.0"
  hop: ">=0.31.0 <0.32.0"
  hop_unittest: ">=0.1.0 <0.2.0"
